name: '.buildme - Simple Build Action'
description: 'Automatically searches for .buildme files in your repository and builds the associated projects with npm.'
author: 'Florian Narr - KLIXPERT.io'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        
    - name: Find and build projects
      shell: bash
      run: ${{ github.action_path }}/buildme.sh